### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by galuhsahid** [pandanistas/pandanistas.github.io#4]
Add a code of conduct section to the website

**Comment by martinagvilas** [comment]
What about using the [NumFOCUS](https://numfocus.org/code-of-conduct) code of conduct?

**Comment by galuhsahid** [comment]
Agreed, maybe we can have the short version on our website, & then have a link to the full page +  link to the CoC reporting form. What do you think?

**Comment by martinagvilas** [comment]
Makes sense! I will assign this issue to myself.
